"""
extract_segments.py — Extract dyrfakt and listener questions from transcripts.

Reads data/transcripts/{id}.json, finds the relevant segments, and asks Claude
to extract the animal fact and listener question for each episode.

Writes to data/segments/{id}.json:
    {
        "episode_id": "...",
        "episode_title": "...",
        "pub_date": "...",
        "dyrfakt": "Geparder kan ikke brøle...",   // or null
        "listener_question": "...",                 // or null
        "model": "claude-haiku-4-5"
    }

Usage:
    python scripts/extract_segments.py              # all transcribed episodes
    python scripts/extract_segments.py --limit 3    # first N pending
    python scripts/extract_segments.py --episode-id <id>

Requires:
    ANTHROPIC_API_KEY environment variable
"""

import argparse
import gzip
import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Optional

import anthropic
from pydantic import BaseModel

# Auto-load .env from project root if present
_env_file = Path(__file__).parent.parent / ".env"
if _env_file.exists():
    for _line in _env_file.read_text(encoding="utf-8").splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _k, _, _v = _line.partition("=")
            if not os.environ.get(_k.strip()):
                os.environ[_k.strip()] = _v.strip()

DATA_DIR = Path(__file__).parent.parent / "data"
TRANSCRIPTS_DIR = DATA_DIR / "transcripts"
SEGMENTS_DIR = DATA_DIR / "segments"
META_FILE = DATA_DIR / "episodes_meta.json"

MODEL = "claude-haiku-4-5"

# Context window around each marker (chars before + after)
CTX_BEFORE = 100
CTX_AFTER = 1500

SYSTEM_PROMPT = """\
You extract specific recurring segments from Danish podcast transcripts.
The podcast is called "Videnskabeligt Udfordret" hosted by Mark and Flemming.

The transcript is generated by automatic speech recognition and contains errors:
misspelled words, phonetic substitutions, and garbled proper nouns. When extracting,
output correct standard Danish — fix obvious transcription errors in your output.

Two recurring segments appear near the end of each episode:
1. DYRFAKT — an animal fact, introduced with a word resembling "dyrfakt" in the text
   (may be misspelled as "dyrfægt", "dyrefækt", "dyrefact", "dyrefagt", "dyreffekt", etc.).
   Extract only the fact itself (e.g. "Geparder kan ikke brøle, de kan kun miaue ligesom en huskat").
   Do not include framing like "dagens dyrfakt er..." — just the fact.

2. LYTTERSPØRGSMÅL — a listener question, introduced with "lytterspørgsmål" in the text.
   Extract the topic or content of the question concisely (1–2 sentences max).
   Do not include framing like "Vi har et fra..." — just the question.

Return null for either field if the segment is absent or unclear in the excerpt.
Return JSON only, no explanation."""


class SegmentExtraction(BaseModel):
    dyrfakt: Optional[str]
    listener_question: Optional[str]


def find_context(text: str, pattern: str) -> str | None:
    """Return a snippet of text around the first regex match, or None if not found."""
    m = re.search(pattern, text, re.IGNORECASE)
    if not m:
        return None
    start = max(0, m.start() - CTX_BEFORE)
    end = min(len(text), m.start() + CTX_AFTER)
    return text[start:end]


# Whisper mishears "dyrfakt" in many ways: dyrfægt, dyrefækt, dyrefact, dyrefagt,
# dyreffekt, dyrfag. The common stem is "dyre?f" followed by some consonant cluster.
DYRFAKT_PATTERN = r"dyre?ff?[aæe]"

def build_user_message(transcript_text: str) -> str:
    dyrfakt_ctx = find_context(transcript_text, DYRFAKT_PATTERN)
    lytter_ctx = find_context(transcript_text, r"lytterspørgsmål")

    parts = []
    if dyrfakt_ctx:
        parts.append(f"DYRFAKT EXCERPT:\n{dyrfakt_ctx}")
    if lytter_ctx:
        parts.append(f"LYTTERSPØRGSMÅL EXCERPT:\n{lytter_ctx}")

    if not parts:
        return "No relevant segments found in this transcript."
    return "\n\n".join(parts)


def extract_segments_sync(
    client: anthropic.Anthropic,
    episode: dict,
) -> dict | None:
    """Extract segments for one episode. Returns the segment dict or None on failure."""
    ep_id = episode["id"]
    title = episode.get("title", ep_id)

    gz_path = TRANSCRIPTS_DIR / f"{ep_id}.json.gz"
    json_path = TRANSCRIPTS_DIR / f"{ep_id}.json"
    if not gz_path.exists() and not json_path.exists():
        return None

    out_path = SEGMENTS_DIR / f"{ep_id}.json"
    if out_path.exists():
        print(f"  SKIP  {title[:60]} (already extracted)")
        return json.loads(out_path.read_text(encoding="utf-8"))

    if gz_path.exists():
        transcript_data = json.loads(gzip.decompress(gz_path.read_bytes()).decode("utf-8"))
    else:
        transcript_data = json.loads(json_path.read_text(encoding="utf-8"))
    transcript_text = transcript_data.get("text", "")
    if not transcript_text:
        print(f"  SKIP  {title[:60]} (empty transcript)")
        return None

    user_message = build_user_message(transcript_text)

    try:
        print(f"  START {title[:60]}")
        response = client.messages.parse(
            model=MODEL,
            max_tokens=256,
            system=[{
                "type": "text",
                "text": SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }],
            messages=[{"role": "user", "content": user_message}],
            output_format=SegmentExtraction,
        )
        result = response.parsed_output

        out = {
            "episode_id": ep_id,
            "episode_title": title,
            "pub_date": episode.get("date", ""),
            "dyrfakt": result.dyrfakt,
            "listener_question": result.listener_question,
            "model": MODEL,
        }

        out_path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")

        flags = []
        if result.dyrfakt:
            flags.append("dyrfakt")
        if result.listener_question:
            flags.append("lytter")
        print(f"  DONE  {title[:60]} [{', '.join(flags) or 'none'}]")
        return out

    except anthropic.APIError as e:
        print(f"  ERROR {title[:60]} — {e}", file=sys.stderr)
        return None


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract dyrfakt + listener Q from transcripts")
    parser.add_argument("--limit", type=int, default=None, help="Process at most N episodes")
    parser.add_argument("--episode-id", help="Process a single episode by ID")
    args = parser.parse_args()

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY environment variable is not set.", file=sys.stderr)
        sys.exit(1)

    if not META_FILE.exists():
        print(f"ERROR: {META_FILE} not found.", file=sys.stderr)
        sys.exit(1)

    episodes = json.loads(META_FILE.read_text(encoding="utf-8"))

    if args.episode_id:
        episodes = [ep for ep in episodes if ep["id"] == args.episode_id]
        if not episodes:
            print(f"ERROR: Episode ID '{args.episode_id}' not found.", file=sys.stderr)
            sys.exit(1)
    else:
        # Only process episodes that have a transcript but no segments yet
        pending = [
            ep for ep in episodes
            if (
                (TRANSCRIPTS_DIR / f"{ep['id']}.json.gz").exists()
                or (TRANSCRIPTS_DIR / f"{ep['id']}.json").exists()
            )
            and not (SEGMENTS_DIR / f"{ep['id']}.json").exists()
        ]
        if args.limit:
            pending = pending[: args.limit]
        episodes = pending

    print(f"Segment extraction")
    print(f"  Model:    {MODEL}")
    print(f"  Episodes: {len(episodes)} pending")
    print()

    if not episodes:
        print("Nothing to do.")
        return

    SEGMENTS_DIR.mkdir(parents=True, exist_ok=True)
    client = anthropic.Anthropic(api_key=api_key)

    done = errors = 0
    for ep in episodes:
        result = extract_segments_sync(client, ep)
        if result is None:
            errors += 1
        elif (SEGMENTS_DIR / f"{ep['id']}.json").exists():
            done += 1
        time.sleep(1.5)  # stay within 50 req/min rate limit

    print(f"\nSummary")
    print(f"  Done:   {done}")
    print(f"  Errors: {errors}")


if __name__ == "__main__":
    main()
